language: java
before_install:
  - |
    pushd .. && wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz && \
    tar -xzvf protobuf-2.5.0.tar.gz && \
    pushd protobuf-2.5.0 && ./configure --prefix=/usr && make && sudo make install && popd && popd
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
deploy:
  provider: releases
  api_key:
    secure: YtSyDKT1P7acHFC3N8LLfiob+gN1O1UgndDDJLvYFs2XkJegI0i67qH/LvrDEcyWZZ0Yj/eiL68AyHuMjjGadRZT261lTS14+yRfPbnAsgs/YqK3MK4TiQVnS9GV3mgp0UGFWpMrija1VhI1QVFV8e7RZLkW/XjN1FbqPPE34xcbheXgv2tQ9PtlB2Kdcwti2Qy9gdP95taC3khlsTyefxVak4+2vB7box4us0xcyJ0XWLDPa0jcnA7sb7/aYTLAdhXRLsDPVgaskgLBjWNYIoEtA1iVJQkNMzVZ/a/MtAYuSDPcJwhuckzici0yw64wL7wSVehJhX3i0XZ3PqGIsLG5hXCgS2ewqiEgmjwaphutm129gDRlRDW1i7mm3bld8blfGMI58mXar6uYxmqTdjgczgREhB7mBG9cQb0dhms70EskWSlPLR8tTqfvgLSFmt00zDkfLXt6sV9u8dwXp/1GLX2kmGty4ldVDzDvCZm9GSklHXCgrY+NUaxyZOEWzYx+iFt37KTVswGMnGEHxUkHBhK6w+Quj9/Vm8pY0t4xqLq51g5e9JPrU8NGMFonhBfkFHD54cTxP3uyx99lxsNOqUMqQBMeNgFZlPaadiwYhqk3ApyIPWJ8VcxaD4EiabCidfDPz3rtvaFTdlu+cBZ+/9qkZaseettAKsrlKWA=
  file: target/*.jar
  skip_cleanup: true
